Repository EdiGlacUQ/fenics_ice, pull requests merged in 2022-03, with the labels that each got.

#53 multiply misfit by 0.5 factor
  example_cases/ice_stream/ice_stream.toml
  example_cases/ismipc_rc_1e6/ismipc_rc_1e6.toml
  example_cases/smith_glacier/smith.toml
  fenics_ice/solver.py
Labels: bug

#62 Define the pytest python_files setting
  setup.cfg
Labels: test maintenance

#69 Output features
  example_cases/ice_stream/ice_stream.toml
  example_cases/ice_stream_varres/ice_stream_varres.toml
  example_cases/ismipc_30x30/ismipc_30x30.toml
  example_cases/ismipc_30x30/momsolve.toml
  example_cases/ismipc_40x40/ismipc_40x40.toml
  example_cases/ismipc_40x40/momsolve.toml
  example_cases/ismipc_rc_1e4/ismipc_rc_1e4.toml
  example_cases/ismipc_rc_1e4/momsolve.toml
  example_cases/ismipc_rc_1e6/ismipc_rc_1e6.toml
  example_cases/ismipc_rc_1e6/momsolve.toml
  example_cases/ismipc_rc_1e6_parallel/ismipc_rc_1e6.toml
  example_cases/ismipc_rc_1e6_parallel/momsolve.toml
  example_cases/smith_glacier/smith.toml
  fenics_ice/config.py
  fenics_ice/eigendecomposition.py
  fenics_ice/fenics_util.py
  fenics_ice/inout.py
  fenics_ice/model.py
  fenics_ice/solver.py
  fenics_ice/test_domains.py
  input/smith_500m_input/data_preproc_script.py
  runs/process_eigendec.py
  runs/run_balancemeltrates.py
  runs/run_eigendec.py
  runs/run_errorprop.py
  runs/run_forward.py
  runs/run_inv.py
  runs/run_invsigma.py
Labels: enhancement
